[package]
name = "voronotalt"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
nalgebra = "0.33"
rayon = "1.10"

[dev-dependencies]
approx = "0.5"
criterion = "0.5"

[[bench]]
name = "tessellation"
harness = false
